version: '3.9'

services:
  api:
    image: aluno/redundante-api:1.0
    ports:
      - "8080:3000"
    networks:
      - appnet
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: on-failure

  monitor:
    image: alpine
    command: sh -c "while true; do wget -qO- http://api:3000/info; echo; sleep 3; done"
    networks:
      - appnet

networks:
  appnet:
    driver: overlay
